<a href="https://colab.research.google.com/github/SuuuHyeon/machine-learning/blob/main/machine_learning_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 머신러닝 기초 정리 1 - NumPy

## NumPy란?
  - NumPy는 파이썬에서 수치 데이터를 처리하기 위한 핵심라이브러리  
  - 머신러닝의 기초가 되는 벡터/행렬 연산을 빠르게 수행할 수 있도록 도와줌  
  - 머신러닝 모델 학습에 필요한 데이터 전처리, 수학적 연산, 통계 분석 등을 수행할 때 가장 기본적으로 사용됨

In [6]:
# numpy 설치는 pip install numpy 실행

# numpy import하기
import numpy as np

## 1. 배열 생성 (Array Creation)
- 기본 데이터 구조: ndarray  
- 리스트로부터 배열 생성  
- 다차원 배열도 생성 가능


In [7]:
import numpy as np

array1 = np.array([1,2,3])
print('array1 type :', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array ([[1,2,3], [2,3,4]])
print('array2 type :', type(array2))
print('array2 array 형태 :', array2. shape)

array3 = np.array ([[1,2,3]])
print('array3 array 형태 : ', type (array3))
print('array3 array 형태 : ', array3. shape)

print(array1.ndim, array2.ndim, array3.ndim)
print('array1 : {:}차원, array2 : {:1} 차원 , array3 : {:2} 차원'
      .format(array1.ndim, array2.ndim, array3.ndim))

array1 type : <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type : <class 'numpy.ndarray'>
array2 array 형태 : (2, 3)
array3 array 형태 :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)
1 2 2
array1 : 1차원, array2 : 2 차원 , array3 :  2 차원


## 2. 배열 속성 (Array Properties)
- 배열 구조, 타입, 크기 등 확인 가능


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)   # 배열 모양: (2, 3)
print(arr.ndim)    # 차원 수: 2
print(arr.dtype)   # 자료형: int64
print(arr.size)    # 총 원소 개수: 6
print(type(arr))   # numpy.ndarray 객체 타입

(2, 3)
2
int64
6
<class 'numpy.ndarray'>


## 3. 배열 생성 함수
- 자주 쓰이는 배열을 쉽게 생성  
- 0, 1, 연속값 등 자동 생성


In [13]:
print(np.zeros((2, 3)), '\n')        # 2행 3열, 모든 원소가 0
print(np.ones((2, 3)), '\n')         # 2행 3열, 모든 원소가 1
print(np.arange(0, 10, 2), '\n')     # 0부터 10까지 2 간격으로 생성
print(np.linspace(0, 1, 5), '\n')    # 0부터 1까지 5개 구간 등분
print(np.eye(3))                     # 3x3 단위 행렬

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[0 2 4 6 8] 

[0.   0.25 0.5  0.75 1.  ] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 4. 인덱싱 & 슬라이싱
- 배열 요소 선택  
- 행/열 접근 가능


In [14]:
a = np.array([[10, 20, 30], [40, 50, 60]])

print(a[0, 1])   # 0행 1열: 20
print(a[:, 1])   # 모든 행, 1열: [20 50]
print(a[1, :])   # 1행 전체: [40 50 60]

20
[20 50]
[40 50 60]


## 5. 배열 연산
- 벡터 연산, 스칼라 연산 지원  
- 조건 연산도 가능


In [15]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)     # [11 22 33] - 요소별 덧셈
print(a * 2)     # [2 4 6] - 스칼라 곱
print(a > 1)     # [False True True] - 조건 연산 결과

[11 22 33]
[2 4 6]
[False  True  True]


## 6. 브로드캐스팅
- 모양이 다른 배열끼리 연산 가능  
- 자동 확장 방식 적용


In [16]:
a = np.array([[1], [2], [3]])      # (3,1) 배열
b = np.array([10, 20, 30])         # (3,) 배열

print(a + b)  # (3,3)로 확장되어 연산됨

[[11 21 31]
 [12 22 32]
 [13 23 33]]


## 7. 배열 형태 변경 & 전치
- reshape: 배열 구조 변경  
- 전치 (행 ↔ 열)

In [17]:
a = np.arange(12)         # 0~11까지 1차원 배열
b = a.reshape((3, 4))     # 3행 4열 배열로 변경
c = np.transpose(b)       # 전치

print('a\n', a)
print('b\n', b)
print('c\n', c)

a
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
b
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
c
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## 8. 통계 함수
- 합, 평균, 표준편차 등 기본 통계 지원

In [18]:
data = np.array([1, 2, 3, 4, 5])

print(np.sum(data))    # 합계: 15
print(np.mean(data))   # 평균: 3.0
print(np.std(data))    # 표준편차: 1.414...
print(np.max(data))    # 최댓값: 5
print(np.min(data))    # 최솟값: 1

15
3.0
1.4142135623730951
5
1


# 머신러닝 기초 정리 2 - Pandas

## Pandas란?
- 표 형태의 데이터를 다루기 위한 대표적인 파이썬 라이브러리  
- CSV, Excel 파일 등 다양한 소스의 데이터를 불러와 가공, 분석, 시각화 가능


In [ ]:
# pandas 설치: !pip install pandas
import pandas as pd

## 1. Series와 DataFrame
- Pandas의 핵심 데이터 구조: Series(1차원), DataFrame(2차원)  
- DataFrame은 엑셀과 비슷한 표 구조로, 행과 열로 구성됨

In [29]:
# Series 생성
s = pd.Series([10, 20, 30])
print("Series:\n", s)

# DataFrame 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Score': [85, 90, 95]
}
df = pd.DataFrame(data)
print("\nDataFrame:\n", df)

Series:
 0    10
1    20
2    30
dtype: int64

DataFrame:
       Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95


## 2. 데이터 불러오기
- read_csv, read_excel 등을 통해 외부 파일 불러오기 가능  
- 기본적으로 CSV 포맷을 가장 많이 사용

In [52]:
# titanic_train.csv 파일 가져오기
titanic_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/titanic_train.csv')

## 3. DataFrame 기본 정보 확인
- 데이터 형태나 간단한 통계, 컬럼 정보 등 전체 구조를 파악하는 데 유용  
- 머신러닝에서는 결측치나 컬럼 스케일링 전에 먼저 확인 필요


In [33]:
print(titanic_df.shape, '\n')       # (행, 열) 형태 확인
print(titanic_df.columns, '\n')     # 컬럼 이름 확인
print(titanic_df.info(), '\n')      # 데이터 타입, 결측치 여부 확인
print(titanic_df.describe(), '\n')  # 수치형 컬럼에 대한 통계 요약

(891, 12) 

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object') 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None 

       PassengerId    Survived      Pclass         Age       SibSp  \


## 4. 데이터 선택 및 필터링
- 행/열 선택, 조건을 이용한 필터링 가능  
- loc, iloc, 조건식을 통해 다양한 방식으로 데이터 접근

In [42]:
# 열 선택
print(titanic_df['Name'], '\n')           # Name 열만 선택

# 행 선택
print(titanic_df.iloc[0], '\n')          # 첫 번째 행 (인덱스로)
print(titanic_df.loc[1], '\n')           # 첫 번째 행 (라벨로)

# 조건 필터링
print(titanic_df[titanic_df['Age'] > 70])  # Age가 70 초과인 행 필터링

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object 

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket              

## 5. 결측치 처리
- 머신러닝에서는 결측치를 제거하거나 적절히 채우는 것이 중요
- dropna() 또는 fillna()로 처리

In [53]:
# 결측치 확인
print(titanic_df.isna().sum())   # isna()를 활용하여 각 컬럼별 결측치 개수 확인

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [55]:
# fillna()로 Missing 데이터를 대체

# Cabin 데이터 처리
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C000        S

In [56]:
# Age 데이터 처리
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C000        S

In [59]:
# Embarked 데이터 처리
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')

In [58]:
# 확인
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

## DataFrame 컬럼 접근, 수정, 삭제
- DataFrame에서 컬럼에 접근하거나 값을 수정, 삭제하는 것은 머신러닝 전처리의 핵심  
- 특히 새로운 파생 피처를 만들거나 필요 없는 컬럼을 제거할 때 자주 사용

### 추가

In [85]:
titanic_df.head(3)

PassengerId  Survived                                               Name  \
0            1         0                            Braund, Mr. Owen Harris   
1            2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3         1                             Heikkinen, Miss. Laina   

      Sex   Age  SibSp  Parch            Ticket     Fare Embarked  
0    male  22.0      1      0         A/5 21171   7.2500        S  
1  female  38.0      1      0          PC 17599  71.2833        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250        S

In [86]:
titanic_df['Age*10'] = titanic_df['Age'] * 10   # Age * 10의 값이 들어간 열을 추가
titanic_df.head(3)

PassengerId  Survived                                               Name  \
0            1         0                            Braund, Mr. Owen Harris   
1            2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3         1                             Heikkinen, Miss. Laina   

      Sex   Age  SibSp  Parch            Ticket     Fare Embarked  Age*10  
0    male  22.0      1      0         A/5 21171   7.2500        S   220.0  
1  female  38.0      1      0          PC 17599  71.2833        C   380.0  
2  female  26.0      0      0  STON/O2. 3101282   7.9250        S   260.0

### 수정

In [63]:
titanic_df['Pclass'].head(3) # Pclass 값 확인

0    3
1    1
2    3
Name: Pclass, dtype: int64

In [64]:
titanic_df['Pclass'] = 1111     # Pclass 값 1111로 수정
titanic_df['Pclass'].head(3)    # 확인

0    1111
1    1111
2    1111
Name: Pclass, dtype: int64

### 삭제
- drop() 함수를 사용해 컬럼 삭제 가능  
- axis=1은 열, 0은 행 기준, inplace=True는 원본에 적용

In [65]:
titanic_df.head(3)      # 데이터 삭제 전

PassengerId  Survived  Pclass  \
0            1         0    1111   
1            2         1    1111   
2            3         1    1111   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C000        S

In [67]:
titanic_drop_df = titanic_df.drop('Pclass', axis=1)
print("##### 삭제 후 데이터 #####\n", titanic_drop_df.head(3), '\n')
print("##### 원본 데이터 #####\n", titanic_df.head(3))

##### 삭제 후 데이터 #####
    PassengerId  Survived                                               Name  \
0            1         0                            Braund, Mr. Owen Harris   
1            2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3         1                             Heikkinen, Miss. Laina   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    male  22.0      1      0         A/5 21171   7.2500  C000        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250  C000        S   

##### 원본 데이터 #####
    PassengerId  Survived  Pclass  \
0            1         0    1111   
1            2         1    1111   
2            3         1    1111   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Brig

In [84]:
print('##### 원본 #####\n', titanic_df.head(3), '\n')

# 삭제
titanic_drop_df = titanic_df.drop('Cabin', axis=1, inplace=True)
print('##### inplace = Ture 적용 후 반환된 값 #####\n', titanic_drop_df, '\n')
print('##### inplace = Ture 적용 후 원본 데이터 #####\n', titanic_df.head(3))

##### 원본 #####
    PassengerId  Survived                                               Name  \
0            1         0                            Braund, Mr. Owen Harris   
1            2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3         1                             Heikkinen, Miss. Laina   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    male  22.0      1      0         A/5 21171   7.2500  C000        S  
1  female  38.0      1      0          PC 17599  71.2833  C000        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250  C000        S   

##### inplace = Ture 적용 후 반환된 값 #####
 None 

##### inplace = Ture 적용 후 원본 데이터 #####
    PassengerId  Survived                                               Name  \
0            1         0                            Braund, Mr. Owen Harris   
1            2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3         1                      