<a href="https://colab.research.google.com/github/SuuuHyeon/machine-learning/blob/main/machine_learning_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 머신러닝 기초 정리 1 - NumPy

## NumPy란?
  - NumPy는 파이썬에서 수치 데이터를 처리하기 위한 핵심라이브러리  
  - 머신러닝의 기초가 되는 벡터/행렬 연산을 빠르게 수행할 수 있도록 도와줌  
  - 머신러닝 모델 학습에 필요한 데이터 전처리, 수학적 연산, 통계 분석 등을 수행할 때 가장 기본적으로 사용됨

In [6]:
# numpy 설치는 pip install numpy 실행

# numpy import하기
import numpy as np

## 1. 배열 생성 (Array Creation)
- 기본 데이터 구조: ndarray  
- 리스트로부터 배열 생성  
- 다차원 배열도 생성 가능


In [7]:
import numpy as np

array1 = np.array([1,2,3])
print('array1 type :', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array ([[1,2,3], [2,3,4]])
print('array2 type :', type(array2))
print('array2 array 형태 :', array2. shape)

array3 = np.array ([[1,2,3]])
print('array3 array 형태 : ', type (array3))
print('array3 array 형태 : ', array3. shape)

print(array1.ndim, array2.ndim, array3.ndim)
print('array1 : {:}차원, array2 : {:1} 차원 , array3 : {:2} 차원'
      .format(array1.ndim, array2.ndim, array3.ndim))

array1 type : <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type : <class 'numpy.ndarray'>
array2 array 형태 : (2, 3)
array3 array 형태 :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)
1 2 2
array1 : 1차원, array2 : 2 차원 , array3 :  2 차원


## 2. 배열 속성 (Array Properties)
- 배열 구조, 타입, 크기 등 확인 가능


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)   # 배열 모양: (2, 3)
print(arr.ndim)    # 차원 수: 2
print(arr.dtype)   # 자료형: int64
print(arr.size)    # 총 원소 개수: 6
print(type(arr))   # numpy.ndarray 객체 타입

(2, 3)
2
int64
6
<class 'numpy.ndarray'>


## 3. 배열 생성 함수
- 자주 쓰이는 배열을 쉽게 생성  
- 0, 1, 연속값 등 자동 생성


In [13]:
print(np.zeros((2, 3)), '\n')        # 2행 3열, 모든 원소가 0
print(np.ones((2, 3)), '\n')         # 2행 3열, 모든 원소가 1
print(np.arange(0, 10, 2), '\n')     # 0부터 10까지 2 간격으로 생성
print(np.linspace(0, 1, 5), '\n')    # 0부터 1까지 5개 구간 등분
print(np.eye(3))                     # 3x3 단위 행렬

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[0 2 4 6 8] 

[0.   0.25 0.5  0.75 1.  ] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 4. 인덱싱 & 슬라이싱
- 배열 요소 선택  
- 행/열 접근 가능


In [14]:
a = np.array([[10, 20, 30], [40, 50, 60]])

print(a[0, 1])   # 0행 1열: 20
print(a[:, 1])   # 모든 행, 1열: [20 50]
print(a[1, :])   # 1행 전체: [40 50 60]

20
[20 50]
[40 50 60]


## 5. 배열 연산
- 벡터 연산, 스칼라 연산 지원  
- 조건 연산도 가능


In [15]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)     # [11 22 33] - 요소별 덧셈
print(a * 2)     # [2 4 6] - 스칼라 곱
print(a > 1)     # [False True True] - 조건 연산 결과

[11 22 33]
[2 4 6]
[False  True  True]


## 6. 브로드캐스팅
- 모양이 다른 배열끼리 연산 가능  
- 자동 확장 방식 적용


In [16]:
a = np.array([[1], [2], [3]])      # (3,1) 배열
b = np.array([10, 20, 30])         # (3,) 배열

print(a + b)  # (3,3)로 확장되어 연산됨

[[11 21 31]
 [12 22 32]
 [13 23 33]]


## 7. 배열 형태 변경 & 전치
- reshape: 배열 구조 변경  
- 전치 (행 ↔ 열)

In [17]:
a = np.arange(12)         # 0~11까지 1차원 배열
b = a.reshape((3, 4))     # 3행 4열 배열로 변경
c = np.transpose(b)       # 전치

print('a\n', a)
print('b\n', b)
print('c\n', c)

a
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
b
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
c
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## 8. 통계 함수
- 합, 평균, 표준편차 등 기본 통계 지원

In [18]:
data = np.array([1, 2, 3, 4, 5])

print(np.sum(data))    # 합계: 15
print(np.mean(data))   # 평균: 3.0
print(np.std(data))    # 표준편차: 1.414...
print(np.max(data))    # 최댓값: 5
print(np.min(data))    # 최솟값: 1

15
3.0
1.4142135623730951
5
1
